#!/bin/sh

case "$1" in
    lock)
        setxkbmap -layout us && betterlockscreen -l dim
        ;;
    logout)
        setxkbmap -layout us && i3-msg exit
        ;;
    suspend)
        setxkbmap -layout us && betterlockscreen -l && systemctl suspend
        ;;
    hibernate)
        setxkbmap -layout us && betterlockscreen -l && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

