#!/bin/sh

case "$1" in
    lock)
        betterlockscreen --lock dim --text "Get inspired from everywhere."
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        betterlockscreen -l && systemctl suspend
        ;;
    hibernate)
        betterlockscreen -l && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

